apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-mtr-prateleira
  namespace: job-mtr-prateleira
spec:
  jobTemplate:
    spec:
      backoffLimit: 1
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: job-mtr-prateleira
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: env-mtr-prateleira
                - secretRef:
                    name: chaves-mtr-prateleira
              image: >-
                gcr.io/
              name: executor-mtr-prateleira
              ports:
                - containerPort: 5000
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
          restartPolicy: Never
  schedule: 0 18 * * 1-5
  
  ---
  apiVersion: v1
kind: Namespace
metadata:
  name: job-mtr-prateleira
