apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","targetAverageValue":"800m"}}]'
  name: renda
  namespace: renda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: renda
  minReplicas: 4
  maxReplicas: 8
